- hosts: 127.0.0.1
  connection: local
  vars:
    links:
      - http://demo9289130.mockable.io/status
      - http://demo9289130.mockable.io/status

  tasks:
  - name: get url response
    shell: curl {{item}}
    register: res
    with_items: "{{links}}"

  - fail:
      msg: "Invalid Status"
    when: ('{{ (item | from_json).state}}' != "RUNNING")
    with_items: "{{res.results | map(attribute='stdout') | list }}"
